extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  eqeqeq:
    - "warn"
    - "allow-null"
  prefer-const:
    - "warn"
  semi:
    - "warn"
  no-unused-vars:
    - "warn"
  comma-dangle:
    - "off"
  no-console:
    - "off"
  no-tabs:
    - "off"
  indent:
    - "warn"
    - "tab"
    - SwitchCase: 1
  norestrictedsyntax:
    - "off"
  padded-blocks:
    - "off"
  spaced-commment:
    - "off"
  array-bracket-spacing:
    - "warn"
    - "always"
  computed-property-spacing:
    - "warn"
    - "always"
  space-in-parens:
    - "warn"
    - "always"
  import/prefer-default-export:
    - "off"
