extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  eqeqeq:
    - "warn"
    - "allow-null"
  prefer-const:
    - "warn"
  semi:
    - "warn"
  no-unused-vars:
    - "warn"
  comma-dangle:
    - "off"
  no-console:
    - "off"
  no-tabs:
    - "off"
  indent:
    - "warn"
    - "tab"
